version: "3"
services:
  ms:
    image: metasploitframework/metasploit-framework:latest
    links:
      - db
    ports:
      - 44444-44544:44444-44544
    volumes:
      - ./.msf4:/root/.msf4:Z
      - ./data:/root/data:Z
  db:
    image: postgres:10-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local

